language: python
python:
  - "3.6"

install:
  - pip install  -r requirements.txt
  - pip install coveralls

services:
  - Postgresql

before_script:
  - psql -c 'create database "testdb";' -U postgres

script:
  - nosetests --exe -v --with-coverage

after_success :
  - coveralls